/**
 * Seed product data for Protect Life Sciences (CommonJS for server seeding).
 */

const seedProducts = [
  {
    id: 'garcinia-cambogia',
    name: 'Garcinia Cambogia Gummies - Strawberry Flavour, 30 gummies',
    slug: 'garcinia-cambogia',
    short_description: 'Supports weight loss and fat reduction naturally.',
    full_description: 'A natural weight loss solution designed for fat synthesis inhibition and appetite suppression. Crafted with pure Garcinia Cambogia extract to boost metabolism, control cravings, and manage healthy cholesterol levels.',
    ingredients: 'Garcinia Cambogia Extract 250mg',
    benefits: 'Supports Weight Loss|Boosts Metabolism|Sugar Free|Appetite Suppression|Fat Synthesis Inhibition|Cholesterol Management',
    price: 1080,
    image_url: '/images/products/garcinia-cambogia.jpg',
    image_urls: ['/images/products/garcinia-cambogia.jpg'],
    category: 'Weight Management',
    is_featured: 1,
  },
  {
    id: 'apple-cider-vinegar',
    name: 'Apple Cider Vinegar Gummies - Apple Flavour, 30 gummies',
    slug: 'apple-cider-vinegar',
    short_description: 'Supports digestive health and weight management.',
    full_description: 'A delicious apple-flavored gummy to help manage blood sugar levels, improve gut health, boost digestion, and support overall weight management goals without the sour taste of liquid ACV.',
    ingredients: 'Apple Cider Vinegar 50mg, Beet Root 50mg',
    benefits: 'Weight Management|Digestion & Gut Health|Sugar Free|Blood Sugar Management|Antimicrobial Properties',
    price: 880,
    image_url: '/images/products/apple-cider-vinegar.jpg',
    image_urls: ['/images/products/apple-cider-vinegar.jpg'],
    category: 'Weight Management',
    is_featured: 1,
  },
  {
    id: 'magnesium',
    name: 'Magnesium Gummies - Cherry Flavour, 30 gummies',
    slug: 'magnesium',
    short_description: 'Essential mineral support for muscle, nerve, and mental health.',
    full_description: 'Premium Magnesium gummies with Vitamin B6 and FOS. Supports healthy muscle and nerve function, promotes restful sleep, reduces fatigue, and supports mental clarity and overall wellbeing.',
    ingredients: 'Elemental Magnesium 220mg, Vitamin B6, FOS (Fructooligosaccharides)',
    benefits: 'Muscle & Nerve Function|Blood Pressure Regulation|Sugar Free|Mental Health & Sleep|Heart Health|Migraine Relief',
    price: 1180,
    image_url: '/images/products/magnesium.jpg',
    image_urls: ['/images/products/magnesium.jpg'],
    category: 'Minerals & Vitamins',
    is_featured: 1,
  },
  {
    id: 'multivitamin',
    name: 'Kids Multivitamin Gummies - Chocolate Flavour, 30 gummies',
    slug: 'kids-multivitamin',
    short_description: 'Growth, brain development, and immunity support for kids.',
    full_description: 'A parent-friendly formulation designed to support growth, immunity, and brain development in children. Made with pharma-grade pure ingredients and zero artificial colors or preservatives.',
    ingredients: 'Vitamin A, Vitamin B1, B2, B3, B6, Biotin, Vitamin C, Vitamin D3, Vitamin E, Minerals',
    benefits: 'Growth & Immunity|Brain Development|Dietary Supplementation|No Artificial Colors',
    price: 780,
    image_url: '/images/products/kids-multivitamin.jpg',
    image_urls: ['/images/products/kids-multivitamin.jpg'],
    category: 'Minerals & Vitamins',
    is_featured: 1,
  },
  {
    id: 'sleep-gummies',
    name: 'Melatonin Sleep Gummies - Vanilla Flavour, 30 gummies',
    slug: 'melatonin',
    short_description: 'Natural nighttime support for deep and restful sleep.',
    full_description: 'A calming blend of Melatonin designed to help you fall asleep faster, stay asleep longer, reduce stress and anxiety, and wake up feeling refreshed.',
    ingredients: 'Melatonin 5mg',
    benefits: 'Deep & Restful Sleep|Reduce Stress & Anxiety|Insomnia|Jet Lag|Circadian Rhythm Disorders',
    price: 780,
    image_url: '/images/products/melatonin.jpg',
    image_urls: ['/images/products/melatonin.jpg'],
    category: 'Wellness',
    is_featured: 1,
  },
  {
    id: 'omega-gummies',
    name: 'Omega Gummies - Coffee Flavour, 30 gummies',
    slug: 'omega-gummies',
    short_description: 'DHA & EPA support for brain, eye, and heart health.',
    full_description: 'Premium Omega-3 fatty acid gummies with DHA and EPA. Supports cognitive function, cardiovascular health, and eye health without the fishy aftertaste.',
    ingredients: 'Fish Oil 100mg, DHA 13.2mg, EPA 2.5mg',
    benefits: 'Brain & Memory Support|Eye Health|Sugar Free|Heart Health|Brain and Mental Health',
    price: 880,
    image_url: '/images/products/omega-gummies.jpg',
    image_urls: ['/images/products/omega-gummies.jpg'],
    category: 'Wellness',
    is_featured: 0,
  },
  {
    id: 'vitamin-c',
    name: 'Vitamin C Gummies - Orange Flavour, 30 gummies',
    slug: 'vitamin-c',
    short_description: 'Powerful immune support with antioxidant protection.',
    full_description: 'High-potency Vitamin C gummies to strengthen your immune system, support collagen production for healthy skin, and provide powerful antioxidant protection against free radicals.',
    ingredients: 'Ascorbic Acid 500mg',
    benefits: 'Immunity Support|Antioxidant|Sugar Free|Skin Health|Collagen Synthesis',
    price: 680,
    image_url: '/images/products/vitamin-c.jpg',
    image_urls: ['/images/products/vitamin-c.jpg'],
    category: 'Immunity',
    is_featured: 1,
  },
  {
    id: 'biotin',
    name: 'Biotin Hair Gummies - Strawberry Flavour, 30 gummies',
    slug: 'biotin',
    short_description: 'Promotes hair growth, stronger nails, and healthy skin.',
    full_description: 'High-strength Biotin gummies enriched with Zinc and Vitamin E to nourish hair follicles, reduce hair fall, strengthen brittle nails, and improve overall skin texture and radiance.',
    ingredients: 'Biotin 10000mcg, Zinc 8mg, Vitamin E 15mg',
    benefits: 'Hair Growth|Reduced Hair Fall|Stronger Nails|Glowing Skin',
    price: 849,
    image_url: '/images/products/hair-skin-nails-gummies.jpg',
    image_urls: ['/images/products/hair-skin-nails-gummies.jpg'],
    category: 'Hair & Skin',
    is_featured: 0,
  },
  {
    id: 'glutathione',
    name: 'Glutathione Gummies - Blueberry Flavour, 30 gummies',
    slug: 'glutathione',
    short_description: 'Skin Radiance and detox support.',
    full_description: 'Crafted with pure Glutathione, Vitamin C, Vitamin E, and Sesbania Grandiflora to promote skin brightening, liver health, and daily detoxification from within.',
    ingredients: 'Glutathione 250mg, Vitamin C 100mg, Vitamin E, Sesbania Grandiflora 20mg',
    benefits: 'Skin Radiance|Detox Support|Skin Lightening/Appearance|Liver Health|Detoxification',
    price: 1580,
    image_url: '/images/products/glutathione.jpg',
    image_urls: ['/images/products/glutathione.jpg'],
    category: 'Hair & Skin',
    is_featured: 1,
  },
  {
    id: 'shilajit-stamina',
    name: 'Shilajit Stamina Gummies - Dark Chocolate Flavour, 30 gummies',
    slug: 'shilajit-stamina',
    short_description: 'Boosts strength, stamina, and energy naturally.',
    full_description: 'A premium wellness formula containing Shilajit, Ashwagandha Extract, and Safed Musli. Promotes sexual health, anti-aging, immunity, and overall energy management.',
    ingredients: 'Shilajit 250mg, Ashwagandha Ext 100mg, Safed Musli 10mg',
    benefits: 'Strength & Vitality|Energy & Stamina|Sugar Free|Sexual Health and Testosterone|Anti-Aging and Immunity',
    price: 1080,
    image_url: '/images/products/shilajit-stamina.jpg',
    image_urls: ['/images/products/shilajit-stamina.jpg'],
    category: 'Wellness',
    is_featured: 1,
  },
  {
    id: 'adult-multivitamin',
    name: 'Adult Multivitamin Gummies - Mango Flavour, 30 gummies',
    slug: 'adult-multivitamin',
    short_description: 'Complete daily nutrition, energy, and vitality.',
    full_description: 'Premium daily multivitamin formulated for adults. Packed with essential Vitamin A, B-Complex (B1, B2, B3, B6, Biotin), Vitamin C, D3, and E with essential minerals to support the immune system and boost vitality.',
    ingredients: 'Vitamin A, Vitamin B1, B2, B3, B6, Biotin, Vitamin C, Vitamin D3, Vitamin E, Minerals',
    benefits: 'Complete Daily Nutrition|Energy & Vitality|Sugar Free|Immune System Support|Dietary Supplementation',
    price: 880,
    image_url: '/images/products/adult-multivitamin.jpg',
    image_urls: ['/images/products/adult-multivitamin.jpg'],
    category: 'Minerals & Vitamins',
    is_featured: 1,
  },
  {
    id: 'collagen-gummies',
    name: 'Collagen Gummies - Cranberry Flavour, 30 gummies',
    slug: 'collagen-gummies',
    short_description: 'Supports skin elasticity and beauty from within.',
    full_description: 'Premium collagen gummies designed to enhance skin elasticity, reduce wrinkles, and promote youthful skin radiance from within.',
    ingredients: 'Collagen Peptide, Vitamin C, Biotin',
    benefits: 'Skin Elasticity|Beauty from Within|Glowing Skin|Reduced Wrinkles',
    price: 980,
    image_url: '/images/products/collagen.jpg',
    image_urls: ['/images/products/collagen.jpg'],
    category: 'Hair & Skin',
    is_featured: 0,
  },
]

module.exports = { seedProducts }
